### ISSUE TITLE
The example from README is wrong?

### ISSUE THREAD

**Issue by dpc** [aidanhs/rsroll#2]
I don't think new rollsum engine

```
    let mut b = rollsum::Bup::new();
```

should be created inside the loop.

**Comment by dpc** [comment]
I have wrote a simple "chunker" so far: https://github.com/dpc/rdedup/blob/master/src/bin.rs#L31 that seem to pass my simple manual tests. There I use rollsum that I create once, at the start. Is that wrong/right?

I plan to develop it into working backup software like bup/zbackup supporting xz and gpg, that I'll along with rdup.

**Comment by dpc** [comment]
Hmmm... Now that I think about it... maybe it should be created every time...

**Comment by aidanhs** [comment]
https://github.com/aidanhs/rollsum-tests/blob/master/test_rsroll.rs - this repo contains huge tests/benchmarks for popular rollsum implementations. Moving it outside the loop breaks some of the tests.

You do need to recreate it every time in order to reset the rollrum. Probability dictates that most of time time it won't matter because the chance of there being an edge within WINDOW_SIZE bytes of the last edge is low for the default settings. However when that does happen, you've ended up with an edge which depends on the content of the previous chunk, defeating deduplication.

**Comment by dpc** [comment]
So shouldn't the example be:

```
    let mut b = rollsum::Bup::new();
    while ofs < buf.len() {
        if let Some(count) = b.find_chunk_edge(&buf[ofs..]) {
            ofs += count;
            println!("found edge at {}", ofs);
            b = rollsum::Bup::new(); // HERE ONLY
        } else {
            println!("end of the line!");
            break
        }
    }
```

In my tests, if the buffer sizes are changed, and relatively small, it's actually quite easy to get different number of chunks on the same data if not done this way.

**Comment by aidanhs** [comment]
I'm pretty sure that does the same thing as my code? In your code every iteration of the loop creates a new rollsum (if it doesn't go into that case of the if, the loop it terminated).

Perhaps I'm missing something - do you have a concrete example of the output differing?

**Comment by dpc** [comment]
Ah, you only process through one `buf` (vec, actually), while in my code I go through series of `buf`-s, and just because a given buffer is over, does not mean the whole data is over.

**Comment by aidanhs** [comment]
Ah that makes more sense. I guess this issue can be closed?

**Comment by dpc** [comment]
Thanks.
